lang: ru

auto-start:
  enabled: true

  # Минимальный онлайн для того чтобы заспавнить моба, если Freeze включён то таймер будет заморожен если онлайн ниже
  min-online: 3

  # Если true, то таймер заморозится если недостаточно игроков
  # Если false, то таймер будет продолжать идти ни смотря на онлайн
  freeze: true

  # Часовой пояс
  zone: GMT+3

  # Если написать time: <число> тогда раз в <число> секунд будет пытаться заспавнить моба
  time: 1800
  # или же можно расписать точное время в которое будут спавниться мобы
  # Время указывается в формате 24 часа, например 17:30 - это 5:30 вечера
  # Можно указывать несколько времён, тогда в каждое из этих времён будет спавниться моб
  # Если указано несколько времён, то они должны быть с отступом в 2 пробела
  # Пример:
#  time:
#    - '10:00;id' # если добавить ";id_моба", то в это время будет именно данный ивент
#    - '21:00' # если же ничего не добавлять, то будет рандомный моб
#    - '23:00'
#    - '17:00:SUNDAY' # да, можно даже поставить даже дни недели


placeholder-show-format: "%weeks% %days% %hours% %minutes% %seconds%"
